<?xml version="1.0" encoding="UTF-8"?><testrun name="UserServiceTest" project="UserTesting" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.example.demo.service.UserServiceTest" time="2.197" displayname="UserServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.UserServiceTest]">
    <testcase name="testGetUsers" classname="com.example.demo.service.UserServiceTest" time="2.112" displayname="testGetUsers()" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.UserServiceTest]/[method:testGetUsers()]">
      <failure>
        <expected>1</expected>
        <actual>3</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;1&gt; but was: &lt;3&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)&#13;
	at com.example.demo.service.UserServiceTest.testGetUsers(UserServiceTest.java:62)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
    <testcase name="testSaveUser" classname="com.example.demo.service.UserServiceTest" time="0.082" displayname="testSaveUser()" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.UserServiceTest]/[method:testSaveUser()]"/>
  </testsuite>
</testrun>
